services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: utkrusht
      POSTGRES_PASSWORD: utkrusht_password
      POSTGRES_DB: ecom_analytics
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql:ro

volumes:
  pgdata:
